### ISSUE TITLE
[BUG]IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

### ISSUE THREAD

**Issue by SUC-DriverOld** [ZFTurbo/Music-Source-Separation-Training#100]
I have updated the repository code to the latest version.

I set `stereo: false` in the config file to train a model. It caused the following bug when validate. This may be due to forgetting to consider mono audio when matching audio length.

```shell
Traceback (most recent call last):                                                                                                                                                                   
  File "/root/miniconda3/envs/msst/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap                                                                                               
    self.run()                                                                                                                                                                                       
  File "/root/miniconda3/envs/msst/lib/python3.10/multiprocessing/process.py", line 108, in run                                                                                                      
    self._target(*self._args, **self._kwargs)                                                                                                                                                        
  File "/root/MSST/msst/valid.py", line 251, in valid_mp                                                                                                                                             
    single_metrics = proc_list_of_files([path], m1, args, config, device, False, False)                                                                                                              
  File "/root/MSST/msst/valid.py", line 149, in proc_list_of_files                                                                                                                                   
    track_metrics = get_metrics(                                                                                                                                                                     
  File "/root/MSST/msst/utils.py", line 693, in get_metrics                                                                                                                                          
    mix = mix[:, :min_length]                                                                                                                                                                        
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```

Currently, I checkout to commit a45d9bc to avoid this bug.

**Comment by ZFTurbo** [comment]
I fixed validation in latest commit. Now it works ok for mono.

**Comment by SUC-DriverOld** [comment]
It works now! Thank you very much!
