### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by ghost** [ZFTurbo/Music-Source-Separation-Training#23]
I got the following error. Please let me know how to resolve it.

Traceback (most recent call last):
  File "C:\Users\Users\desktop\Music-Source-Separation-Training-main\train.py", line 515, in <module>
    train_model(None)
  File "C:\Users\Users\desktop\Music-Source-Separation-Training-main\train.py", line 332, in train_model
    model, config = get_model_from_config(args.model_type, args.config_path)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Users\desktop\Music-Source-Separation-Training-main\utils.py", line 24, in get_model_from_config
    from models.demucs4ht import get_model
  File "C:\Users\Users\desktop\Music-Source-Separation-Training-main\models\demucs4ht.py", line 10, in <module>
    from demucs.demucs import Demucs
ModuleNotFoundError: No module named 'demucs'

**Comment by ZFTurbo** [comment]
```
pip install demucs
```
All required modules are here:
https://github.com/ZFTurbo/Music-Source-Separation-Training/blob/main/requirements.txt

**Comment by ZFTurbo** [comment]
Your python doesn't see the `demucs` module for some reason.

**Comment by danny69boc** [comment]
pip install demucs
Now it works! Thank you.

**Comment by danny69boc** [comment]
Thanks for answering so many questions.
Thanks to you I understand how to use most of them.
I would like to make my own advanced models like the MDX23C.

For example, like separating the metronome sound from the drum sound.
For this, I need to create a learning model from scratch that does not use a pre-training model.
How can I create a new one without using the provided checkpoints?

--start_check_point results/model.ckpt \

**Comment by ZFTurbo** [comment]
Just don't use:
```
--start_check_point results/model.ckpt 
```

In this case training will start from scratch.

**Comment by danny69boc** [comment]
![1713796615009](https://github.com/ZFTurbo/Music-Source-Separation-Training/assets/165942358/c49106d6-342c-4ca0-ad86-13b23716fd6f)

  num_epochs: 1000
  num_steps: 1000

We now have a new model that has been trained from the beginning with the first set of numbers.
However, the separation only generated noise that was not present in any of the data sets.
The noise is like a hum.
Does this mean that I have not learned enough yet?

**Comment by ZFTurbo** [comment]
What was the SDR on validation?

**Comment by danny69boc** [comment]
I was doing a lot of things to solve the problem. Thanks!
The problem was simply a lack of learning rate.
Lerning Rate is getting lower and lower, do you have a target number?
Would it be better to train until it is as close to 0 as possible?
Or should I target the SDR outputted by TEST, if there is something specific?

**Comment by ZFTurbo** [comment]
You can restart from higher LR (using latest weights) after it became too low.

**Comment by danny69boc** [comment]
I see, I understand.
Thanks.
So you don't have to worry so much about LR.

**Comment by Kenus23** [comment]
Python 3.13.0 (tags/v3.13.0:60403a5, Oct  7 2024, 09:38:07) [MSC v.1941 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

= RESTART: C:\Users\user\Desktop\Music-Source-Separation-Training-1.0.9\train.py
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Music-Source-Separation-Training-1.0.9\train.py", line 9, in <module>
    from tqdm.auto import tqdm
ModuleNotFoundError: No module named 'tqdm'
