### ISSUE TITLE
inference error with pretrained mdx23c model

### ISSUE THREAD

**Issue by nukes** [ZFTurbo/Music-Source-Separation-Training#7]
Hi, i run the inference with your pretrained mdx23c model and get following errors:
```bash
(py3.10) python inference.py --model_type mdx23c \                                                                                [17:48:11]
    --config_path configs/config_vocals_mdx23c.yaml \
    --start_check_point pretrained/model_vocals_mdx23c_sdr_10.17.ckpt \
    --input_folder /soundx_speech_data/eval_audio/singing \
    --store_dir separation_results/
Instruments: ['vocals', 'other']
Start from checkpoint: pretrained/model_vocals_mdx23c_sdr_10.17.ckpt
Total tracks found: 7
  0%|                                                                                                                  | 0/7 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/data1/martinzheng/tts/backend/Music-Source-Separation-Training/inference.py", line 99, in <module>
    proc_folder(None)
  File "/data1/martinzheng/tts/backend/Music-Source-Separation-Training/inference.py", line 95, in proc_folder
    run_folder(model, args, config, device, verbose=False)
  File "/data1/martinzheng/tts/backend/Music-Source-Separation-Training/inference.py", line 44, in run_folder
    res = demix_track(config, model, mixture, device)
  File "/data1/martinzheng/tts/backend/Music-Source-Separation-Training/utils.py", line 56, in demix_track
    mix = nn.functional.pad(mix, (border, border), mode='reflect')
NotImplementedError: Only 2D, 3D, 4D, 5D padding with non-constant padding are supported for now
```
any ideas?

**Comment by ZFTurbo** [comment]
I think you have mono audio. I didn't check for correctness and don't convert before.

**Comment by ZFTurbo** [comment]
I added a fix in `inference.py` for mono to stereo conversion.

**Comment by nukes** [comment]
> I added a fix in `inference.py` for mono to stereo conversion.

I just tired, the bug has been fixed.  Great work!
