### ISSUE TITLE
bs_mamba2

### ISSUE THREAD

**Issue by SAER2023** [ZFTurbo/Music-Source-Separation-Training#81]
i am trying to inference bs_mamba2 model_bs_mamba2_ep_11_sdr_6.8723.ckpt show error message `CUDA is available, use --force_cpu to disable it.
Using device:  cuda:0
Exception during load Mamba2 modules: No module named 'mamba_ssm'
Load local torch implementation!
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 11, 11, 11, 11, 11, 11, 11, 11, 23, 23, 23, 23, 23, 23, 23, 23, 46, 46, 46, 46, 46, 46, 46, 46, 92, 92, 121]
Start from checkpoint: /kaggle/input/bs-maba2/model_bs_mamba2_ep_11_sdr_6.8723.ckpt
Instruments: ['drums', 'bass', 'other', 'vocals']
Model load time: 3.55 sec
Total files found: 8
Starting processing track:  /kaggle/input/song-testing/62talal.mp3
Processing audio chunks:   0%|                     | 0/23916748 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/kaggle/working/Music-Source-Separation-Training/inference.py", line 182, in <module>
    proc_folder(None)
  File "/kaggle/working/Music-Source-Separation-Training/inference.py", line 178, in proc_folder
    run_folder(model, args, config, device, verbose=True)
  File "/kaggle/working/Music-Source-Separation-Training/inference.py", line 77, in run_folder
    waveforms = demix(config, model, mix, device, pbar=detailed_pbar, model_type=args.model_type)
  File "/kaggle/working/Music-Source-Separation-Training/utils.py", line 367, in demix
    return demix_track(config, model, mix, device, pbar=pbar)
  File "/kaggle/working/Music-Source-Separation-Training/utils.py", line 146, in demix_track
    x = model(arr)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 186, in forward
    outputs = self.parallel_apply(replicas, inputs, module_kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 201, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 108, in parallel_apply
    output.reraise()
  File "/opt/conda/lib/python3.10/site-packages/torch/_utils.py", line 706, in reraise
    raise exception
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in _worker
    output = module(*input, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/kaggle/working/Music-Source-Separation-Training/models/ts_bs_mamba2.py", line 264, in forward
    sep_output = checkpoint_sequential(self.separator_mask, 2, subband_feature_mask.view(batch_size, nch, self.nband*self.feature_dim, -1))  # B, nband*N, T
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 579, in checkpoint_sequential
    input = checkpoint(
  File "/opt/conda/lib/python3.10/site-packages/torch/_compile.py", line 31, in inner
    return disable_fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 600, in _fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 481, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/function.py", line 574, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 255, in forward
    outputs = run_function(*args)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 566, in forward
    input = functions[j](input)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/kaggle/working/Music-Source-Separation-Training/models/ts_bs_mamba2.py", line 128, in forward
    band_output = self.band_rnn(input.view(B*nch*self.nband, self.feature_dim, -1)).view(B*nch, self.nband, -1, T)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/kaggle/working/Music-Source-Separation-Training/models/ts_bs_mamba2.py", line 106, in forward
    rnn_output =  self.rnn(self.dropout(self.norm(input)).transpose(1, 2).contiguous())
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/kaggle/working/Music-Source-Separation-Training/models/ts_bs_mamba2.py", line 37, in forward
    forward_f_output = self.forward_mamba2(forward_f)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/kaggle/working/Music-Source-Separation-Training/models/ex_bi_mamba2.py", line 82, in forward
    y = self.ssd(x * dt.unsqueeze(-1),
  File "/kaggle/working/Music-Source-Separation-Training/models/ex_bi_mamba2.py", line 112, in ssd
    x = x.reshape(x.shape[0], x.shape[1] // chunk_size, chunk_size, x.shape[2], x.shape[3], )
RuntimeError: shape '[456, 4, 64, 8, 64]' is invalid for input of size 60469248`

i install mamba_ssm
show other error message `CUDA is available, use --force_cpu to disable it.
Using device:  cuda:0
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 11, 11, 11, 11, 11, 11, 11, 11, 23, 23, 23, 23, 23, 23, 23, 23, 46, 46, 46, 46, 46, 46, 46, 46, 92, 92, 121]
Start from checkpoint: /kaggle/input/bs-maba2/model_bs_mamba2_ep_11_sdr_6.8723.ckpt
Instruments: ['drums', 'bass', 'other', 'vocals']
Model load time: 4.90 sec
Total files found: 8
Starting processing track:  /kaggle/input/song-testing/62talal.mp3
Processing audio chunks:   0%|                     | 0/23916748 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/kaggle/working/Music-Source-Separation-Training/inference.py", line 182, in <module>
    proc_folder(None)
  File "/kaggle/working/Music-Source-Separation-Training/inference.py", line 178, in proc_folder
    run_folder(model, args, config, device, verbose=True)
  File "/kaggle/working/Music-Source-Separation-Training/inference.py", line 77, in run_folder
    waveforms = demix(config, model, mix, device, pbar=detailed_pbar, model_type=args.model_type)
  File "/kaggle/working/Music-Source-Separation-Training/utils.py", line 367, in demix
    return demix_track(config, model, mix, device, pbar=pbar)
  File "/kaggle/working/Music-Source-Separation-Training/utils.py", line 146, in demix_track
    x = model(arr)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 186, in forward
    outputs = self.parallel_apply(replicas, inputs, module_kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 201, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 108, in parallel_apply
    output.reraise()
  File "/opt/conda/lib/python3.10/site-packages/torch/_utils.py", line 706, in reraise
    raise exception
AttributeError: Caught AttributeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in _worker
    output = module(*input, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/kaggle/working/Music-Source-Separation-Training/models/ts_bs_mamba2.py", line 264, in forward
    sep_output = checkpoint_sequential(self.separator_mask, 2, subband_feature_mask.view(batch_size, nch, self.nband*self.feature_dim, -1))  # B, nband*N, T
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 579, in checkpoint_sequential
    input = checkpoint(
  File "/opt/conda/lib/python3.10/site-packages/torch/_compile.py", line 31, in inner
    return disable_fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 600, in _fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 481, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/function.py", line 574, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 255, in forward
    outputs = run_function(*args)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 566, in forward
    input = functions[j](input)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/kaggle/working/Music-Source-Separation-Training/models/ts_bs_mamba2.py", line 128, in forward
    band_output = self.band_rnn(input.view(B*nch*self.nband, self.feature_dim, -1)).view(B*nch, self.nband, -1, T)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/kaggle/working/Music-Source-Separation-Training/models/ts_bs_mamba2.py", line 106, in forward
    rnn_output =  self.rnn(self.dropout(self.norm(input)).transpose(1, 2).contiguous())
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/kaggle/working/Music-Source-Separation-Training/models/ts_bs_mamba2.py", line 37, in forward
    forward_f_output = self.forward_mamba2(forward_f)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/mamba_ssm/modules/mamba2.py", line 183, in forward
    out = mamba_split_conv1d_scan_combined(
  File "/opt/conda/lib/python3.10/site-packages/mamba_ssm/ops/triton/ssd_combined.py", line 930, in mamba_split_conv1d_scan_combined
    return MambaSplitConv1dScanCombinedFn.apply(zxbcdt, conv1d_weight, conv1d_bias, dt_bias, A, D, chunk_size, initial_states, seq_idx, dt_limit, return_final_states, activation, rmsnorm_weight, rmsnorm_eps, outproj_weight, outproj_bias, headdim, ngroups, norm_before_gate)
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/function.py", line 574, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/opt/conda/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 455, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/mamba_ssm/ops/triton/ssd_combined.py", line 779, in forward
    causal_conv1d_cuda.causal_conv1d_fwd(rearrange(xBC, "b s d -> b d s"),
AttributeError: 'NoneType' object has no attribute 'causal_conv1d_fwd'`

same error while train 
i tried to train 2stems vocals , instrument
any help

**Comment by ZFTurbo** [comment]
Try: `pip install casual-conv1d>=1.4.0`
https://github.com/state-spaces/mamba/issues/467

**Comment by SAER2023** [comment]
ok work thanks

**Comment by dillfrescott** [comment]
How can this be done on windows?

**Comment by ZFTurbo** [comment]
> How can this be done on windows?

Currently it's only possible in WSL. I tried to add the workaround - but it's doesn't work correctly.

**Comment by dillfrescott** [comment]
Ok gotcha. Thank you!

**Comment by dillfrescott** [comment]
@ZFTurbo I'm on Ubuntu and i have mamba_ssm and causal-conv1d installed and its still saying:

RuntimeError: shape '[912, 4, 64, 8, 64]' is invalid for input of size 120938496

any ideas?

**Comment by KaiMikkelsen** [comment]
> @ZFTurbo I'm on Ubuntu and i have mamba_ssm and causal-conv1d installed and its still saying:
> 
> RuntimeError: shape '[912, 4, 64, 8, 64]' is invalid for input of size 120938496
> 
> any ideas?

I am having the same issue with different shape and input sizes

  File "/project/6002780/kaim/Music-Source-Separation-Training/models/ex_bi_mamba2.py", line 112, in ssd
    x = x.reshape(x.shape[0], x.shape[1] // chunk_size, chunk_size, x.shape[2], x.shape[3], )
RuntimeError: shape '[228, 4, 64, 8, 64]' is invalid for input of size 30234624

I am also having an issue accessing the proper bs_mamba2 modules even after successfully running `pip install mamba-ssm` and `pip install casual-conv1d>=1.4.0`.

Running training script for model: bs_mamba2
Exception during load Mamba2 modules: No module named 'mamba_ssm.modules.mamba2'
Load local torch implementation!

If anyone has any advice that would be appreciated.
