### ISSUE TITLE
IndexError: arrays used as indices must be of integer (or boolean) type

### ISSUE THREAD

**Issue by CyberLykan** [ZFTurbo/Music-Source-Separation-Training#99]
```
CUDA is available, use --force_cpu to disable it.
Using device:  cuda:0
Windows OS detected, using math or mem efficient attention if input tensor is on cuda
Start from checkpoint: D:\My Stuff\Extra Stuff\Music-Source-Separation-Training\checkpoints\MelBand Roformer Inst v1e(mphasis fullness) (by unwa)\inst_v1e.ckpt
Instruments: ['other', 'vocals']
Model load time: 6.46 sec
Total files found: 100 Use sample rate: 44100
Starting processing track:  D:\Downloads\multisong_dataset\song_000_mixture.wav

Processing audio chunks:   0%|          | 0/3131100 [00:00<?, ?it/s]
Processing audio chunks:   8%|7         | 242550/3131100 [00:01<00:15, 181909.55it/s]
Processing audio chunks:  15%|#5        | 485100/3131100 [00:01<00:09, 290538.15it/s]
Processing audio chunks:  23%|##3       | 727650/3131100 [00:02<00:06, 358951.28it/s]
Processing audio chunks:  31%|###       | 970200/3131100 [00:02<00:05, 403601.77it/s]
Processing audio chunks:  39%|###8      | 1212750/3131100 [00:03<00:04, 433407.24it/s]
Processing audio chunks:  46%|####6     | 1455300/3131100 [00:03<00:03, 453854.75it/s]
Processing audio chunks:  54%|#####4    | 1697850/3131100 [00:04<00:03, 472251.62it/s]
Processing audio chunks:  62%|######1   | 1940400/3131100 [00:04<00:02, 480359.87it/s]
Processing audio chunks:  70%|######9   | 2182950/3131100 [00:05<00:01, 485939.81it/s]
Processing audio chunks:  77%|#######7  | 2425500/3131100 [00:05<00:01, 494788.01it/s]
Processing audio chunks:  85%|########5 | 2668050/3131100 [00:06<00:00, 493622.27it/s]
Processing audio chunks:  93%|#########2| 2910600/3131100 [00:06<00:00, 497627.41it/s]
Processing audio chunks: 3153150it [00:07, 502710.73it/s]                             
                                                         
Traceback (most recent call last):
  File "D:\My Stuff\Extra Stuff\Music-Source-Separation-Training\inference.py", line 184, in <module>
    proc_folder(None)
  File "D:\My Stuff\Extra Stuff\Music-Source-Separation-Training\inference.py", line 180, in proc_folder
    run_folder(model, args, config, device, verbose=True)
  File "D:\My Stuff\Extra Stuff\Music-Source-Separation-Training\inference.py", line 94, in run_folder
    waveforms[el] = waveforms[el] / len(full_result)
IndexError: arrays used as indices must be of integer (or boolean) type
Process failed with return code 1
```

**Comment by ZFTurbo** [comment]
There was a bug after yesterday's code refactoring. I fixed it. Can you please check the latest code version?

**Comment by deton24** [comment]
It works now

**Comment by CyberLykan** [comment]
Confirmed working. Keep up the good work!
